# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 175039aed6f152e68dfe90f767e291c770b6e55d157361451047f07ba6cb24406d86cc771f7ba18fdf28b9351a2e688d830e10e23429f45eab961d5801841994

test:
  secret_key_base: 1da05c35edccc1aa0d264b208386641c3318207f5de2228c41fb4e055480c115a85bec59294a1cdb46f27433710aa9d24ac79db7f9f468892e0a6d1fdee581a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
